CREATE DATABASE MARKETING;

USE MARKETING;

CREATE TABLE AREAS(
`ID_AREA` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`NOMBRE` VARCHAR(40) NOT NULL,
`ENCARGADO` VARCHAR(40) NOT NULL);

CREATE TABLE ETHERSHIELD(
`MAC` VARCHAR(30)  PRIMARY KEY NOT NULL,
`ID_AREA` INT NOT NULL,
`FECHA` DATE);

CREATE TABLE SENSOR_ULTRASONICO(
`ID_ULTRA` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`FECHA` DATE NOT NULL,
`TIEMPO`VARCHAR(255),/*CHECAR EL FORMATO DE TIEMPO DE ESPERA*/
`MAC` VARCHAR(30) NOT NULL);

CREATE TABLE SENSOR_TEMPERATURA(
`ID_TEMP` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`FECHA` DATE NOT NULL,
`HUMEDAD` VARCHAR(255),/*CHECAR QUE TIPO DE VALOR REGRESA HUMEDAD*/
`TEMPERATURA` VARCHAR(255),
`MAC` VARCHAR(30) NOT NULL);

CREATE TABLE SENSOR_INFRARROJO(
`ID_INFRA` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`FECHA` DATE NOT NULL,
`CANTIDAD_P` INT NOT NULL,
`MAC` VARCHAR(30) NOT NULL);

/*
CREATE TABLE ESTADISTICA(
`ID_ESTAD` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`MAC` VARCHAR(30) NOT NULL,
`ID_ULTRA` VARCHAR(255) NOT NULL,
`ID_INFRA` INT NOT NULL,
`ID_TEMP` VARCHAR(255) NOT NULL);
*/

ALTER TABLE SENSOR_ULTRASONICO ADD FOREIGN KEY (MAC) REFERENCES ETHERSHIELD(MAC);
ALTER TABLE SENSOR_TEMPERATURA ADD FOREIGN KEY (MAC) REFERENCES ETHERSHIELD(MAC);
ALTER TABLE SENSOR_INFRARROJO ADD FOREIGN KEY (MAC) REFERENCES ETHERSHIELD(MAC);

INSERT INTO AREAS(NOMBRE,ENCARGADO) VALUES ('LINEA BLANCA','JUAN SILVESTRE RAMIREZ BECERRA');
INSERT INTO AREAS(NOMBRE,ENCARGADO) VALUES ('JUGUETERIA','JOSE MARTIN RUIZ COSS');
INSERT INTO AREAS(NOMBRE,ENCARGADO) VALUES ('LENCERIA','ALEJANDRA MACALARA AVILA');

INSERT INTO ETHERSHIELD(MAC,ID_AREA,FECHA) VALUES('0xDE0xAD0xBE0xEF0xFF0xEE',1,'2018-12-12');
INSERT INTO ETHERSHIELD(MAC,ID_AREA,FECHA) VALUES('0x010xAA0xBBxCC0xDE0x02',2,'2018-12-12');
INSERT INTO ETHERSHIELD(MAC,ID_AREA,FECHA) VALUES('0xFE0xAF0xAA0xE10xC20xFF',3,'2018-12-12');
